# Generated by Django 5.0.2 on 2024-02-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_owns_car_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="organization",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
