# Generated by Django 5.0.2 on 2024-02-26 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("license_plate", models.CharField(max_length=20)),
                ("seats_available", models.PositiveIntegerField()),
                ("mileage", models.DecimalField(decimal_places=2, max_digits=8)),
                ("color", models.CharField(max_length=50)),
                ("car_type", models.CharField(max_length=50)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_point", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("starttime", models.DateTimeField()),
                ("endtime", models.DateTimeField()),
                ("fuel_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("available_seats", models.PositiveIntegerField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides",
                        to="rides.car",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides_offered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
