# Generated by Django 5.0.2 on 2024-04-16 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0002_ride_passengers_ride_ride_status_riderequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="fuel_price",
            new_name="price_per_head",
        ),
    ]
