# Generated by Django 5.0.2 on 2024-04-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0003_rename_fuel_price_ride_price_per_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
